/* Generated by tools/gen_amiga_symbols.py from port/amiga/symbols.csv. Do not edit. */
#pragma once

/* Data-hunk globals (D:xxxx offsets for D8/D16/D32) */
#define D_sfx_enabled                            0x0344  /* platform_audio, int */
#define D_g_abortKey                             0x0346  /* platform_video, int */
#define D_blit_busy_spins                        0x0348  /* platform_video, long */
#define D_blit_wait_calls                        0x034C  /* platform_video, long */
#define D_g_numCars                              0x0350  /* game_flow, int */
#define D_g_carsKeepBuf                          0x0352  /* game_flow, int */
#define D_cmap_default                           0x0358  /* platform_video, u16[3] */
#define D_arena_flag                             0x0360  /* platform_video, int */
#define D_blit_params                            0x0362  /* platform_video, struct 0x1E */
#define D_clip_top                               0x0380  /* platform_video, int */
#define D_clip_bottom                            0x0382  /* platform_video, int */
#define D_clip_left                              0x0384  /* platform_video, int */
#define D_clip_right                             0x0386  /* platform_video, int */
#define D_fwm_table                              0x0388  /* platform_video, u16[17] */
#define D_lwm_table                              0x03AA  /* platform_video, u16[17] */
#define D_g_blitTag                              0x03CC  /* title_select, long */
#define D_IntuitionBase                          0x03D0  /* platform_video, ptr */
#define D_GfxBase                                0x03D4  /* platform_video, ptr */
#define D_tick_count                             0x03D8  /* platform_video, u32 */
#define D_joy_dir_table                          0x03DC  /* platform_video, u8[16] */
#define D_vbl_last_dir                           0x03EC  /* platform_video, int */
#define D_gate_row                               0x03EE  /* drive_sim, int */
#define D_gate_col                               0x03F0  /* drive_sim, int */
#define D_ltoa_buf                               0x03F4  /* platform_video, char[11] */
#define D_sfx_installed                          0x0444  /* platform_audio, int */
#define D_sfx_chan                               0x0446  /* platform_audio, struct[4] x 0x1E */
#define D_old_level4_vector                      0x04BE  /* platform_audio, long */
#define D_sfx_tick                               0x04C2  /* platform_audio, long */
#define D_sfx_dma_set                            0x04C6  /* platform_audio, int */
#define D_sfx_saved_intena                       0x04C8  /* platform_audio, int */
#define D_song_installed                         0x04CA  /* platform_audio, int */
#define D_music_enabled                          0x04CC  /* platform_audio, int */
#define D_song_inst_loaded                       0x04CE  /* platform_audio, int */
#define D_note_period_table                      0x0500  /* platform_audio, long[132] */
#define D_note_ticks                             0x0710  /* platform_audio, int[16] */
#define D_song_state                             0x0732  /* platform_audio, int */
#define D_song_any_active                        0x0734  /* platform_audio, int */
#define D_song_data                              0x0736  /* platform_audio, long */
#define D_song_track                             0x073A  /* platform_audio, struct[4] x 0x18 */
#define D_song_dma_on                            0x08BA  /* platform_audio, int */
#define D_song_dma_off                           0x08BC  /* platform_audio, int */
#define D_smus_tempo                             0x08BE  /* platform_audio, int */
#define D_smus_volume                            0x08C0  /* platform_audio, int */
#define D_song_buffer                            0x08C2  /* platform_audio, long */
#define D_testdrive_inst                         0x08C6  /* platform_audio, char*[4] */
#define D_testdrive_oneshot                      0x08D6  /* platform_audio, int[4] */
#define D_song_inst                              0x08DE  /* platform_audio, char*[4] */
#define D_song_oneshot                           0x08EE  /* platform_audio, int[4] */
#define D_CREDITS_PENS                           0x08F6  /* game_flow, int[24] */
#define D_CREDITS_TEXT                           0x0926  /* game_flow, char *[25] */
#define D_HS_DEFAULT_PALETTE                     0x098E  /* game_flow, uint[32] */
#define D_MSG_L1_FLYING                          0x09CE  /* game_flow, char *[3] */
#define D_MSG_L1_COOKING                         0x09DA  /* game_flow, char *[3] */
#define D_MSG_L1_LEARNING                        0x09E6  /* game_flow, char *[3] */
#define D_MSG_L1_GRANDMA                         0x09F2  /* game_flow, char *[3] */
#define D_MSG_L1_SLOW                            0x09FE  /* game_flow, char *[3] */
#define D_MSG_L2_FLYING                          0x0A0A  /* game_flow, char *[3] */
#define D_MSG_L2_COOKING                         0x0A16  /* game_flow, char *[3] */
#define D_MSG_L2_LEARNING                        0x0A22  /* game_flow, char *[3] */
#define D_MSG_L2_GRANDMA                         0x0A2E  /* game_flow, char *[3] */
#define D_MSG_L2_SLOW                            0x0A3A  /* game_flow, char *[3] */
#define D_MSG_TIPS                               0x0A46  /* game_flow, char *[3] */
#define D_g_resultsImage                         0x0A52  /* game_flow, struct Image */
#define D_GAS_SIGN_NAMES                         0x0A66  /* game_flow, long[4] */
#define D_g_titleShapeNames                      0x0A7A  /* title_select, long[44] */
#define D_g_savedA4                              0x0B2A  /* title_select, long */
#define D_near_end                               0x0B2E  /* drive_sim, int */
#define D_gearbox_show                           0x0B30  /* drive_sim, byte[2] */
#define D_gearbox_shown                          0x0B32  /* drive_scene, u8[2] */
#define D_gearbox_always                         0x0B34  /* drive_sim, int */
#define D_steer_lock                             0x0B36  /* drive_sim, int */
#define D_slope_clamp                            0x0B38  /* drive_scene, s8[40] */
#define D_pixel_plane_off                        0x0B60  /* drive_scene, u16 */
#define D_row_scale                              0x0B62  /* drive_scene, u16 */
#define D_row_scale2                             0x0B64  /* drive_scene, u16 */
#define D_row_y                                  0x0B66  /* drive_scene, s32 16.16 */
#define D_row_cx                                 0x0B6A  /* drive_scene, s32 16.16 */
#define D_heading_acc                            0x0B6E  /* drive_scene, s32 16.16 */
#define D_slope_acc                              0x0B72  /* drive_scene, s16 */
#define D_crest_y                                0x0B74  /* drive_scene, s16 */
#define D_row_index                              0x0B76  /* drive_scene, u16 */
#define D_blit_dest                              0x0BEC  /* platform_video, u8 *[5] */
#define D_right_edge                             0x0C00  /* drive_scene, s16 */
#define D_left_edge                              0x0C02  /* drive_scene, s16 */
#define D_first_mask                             0x0C04  /* drive_scene, u16[17] */
#define D_last_mask                              0x0C26  /* drive_scene, u16[17] */
#define D_wheel_pose_other                       0x0C4A  /* drive_scene, s16 */
#define D_wheel_pose_here                        0x0C4C  /* drive_scene, s16 */
#define D_MENU_PALETTE                           0x0C4E  /* game_flow, uint[4] */
#define D_sd_pos                                 0x0C6E  /* drive_sim, long[6] */
#define D_cop_pos                                0x0C82  /* drive_sim, long */
#define D_sd_speed                               0x0C92  /* drive_sim, long[6] */
#define D_cop_speed                              0x0CA6  /* drive_sim, long */
#define D_sd_dodge                               0x0CAA  /* drive_sim, int[6] stride 4 */
#define D_police_slide                           0x0CBE  /* drive_scene, s16 */
#define D_sd_lane                                0x0CC2  /* drive_sim, struct{int lat; int flag}[6] */
#define D_cop_tailing                            0x0CD8  /* drive_sim, int */
#define D_on_pos                                 0x0CF2  /* drive_sim, long[5] */
#define D_on_speed                               0x0D14  /* drive_sim, long[5] */
#define D_on_lane                                0x0D28  /* drive_sim, struct{int lat; int pad}[5] */
#define D_r_same_dir                             0x0D40  /* drive_scene, s32[6] */
#define D_r_oncoming                             0x0D58  /* drive_scene, s32[6] */
#define D_autopilot                              0x0D70  /* drive_sim, int */
#define D_lane_hold                              0x0D72  /* drive_sim, int */
#define D_ticket_frames                          0x0D74  /* drive_sim, int */
#define D_cop_tail_frames                        0x0D76  /* drive_sim, int */
#define D_cop_timer                              0x0D78  /* drive_sim, int */
#define D_cop_mode                               0x0D7A  /* drive_sim, int */
#define D_slot_base_x                            0x0D7C  /* drive_scene, s16 */
#define D_slot_base_lat                          0x0D7E  /* drive_scene, s16 */
#define D_hazard_hit                             0x0D80  /* drive_sim, int */
#define D_first_row_weight                       0x0D82  /* drive_scene, u16 */
#define D_row_centre                             0x0D84  /* drive_scene, s16 */
#define D_speed_limit_table                      0x0D86  /* drive_sim, u8[3] */
#define D_seg_frac                               0x0D8A  /* drive_sim, int */
#define D_half_left                              0x0D8C  /* drive_scene, u16 */
#define D_half_right                             0x0D8E  /* drive_scene, u16 */
#define D_last_left                              0x0D90  /* drive_scene, u16 */
#define D_last_right                             0x0D92  /* drive_scene, u16 */
#define D_car_half_left                          0x0D94  /* drive_scene, u16 */
#define D_car_half_right                         0x0D96  /* drive_scene, u16 */
#define D_wide_road                              0x0D98  /* drive_scene, s16 */
#define D_bump_flag                              0x0D9A  /* drive_sim, int */
#define D_first_unit                             0x0D9C  /* drive_sim, int */
#define D_cloud_heading                          0x0D9E  /* drive_scene, s16 */
#define D_cloud_x                                0x0DA0  /* drive_scene, s32[4] 16.16 */
#define D_speed_limit                            0x0DBC  /* drive_sim, int */
#define D_radar_zone_ctr                         0x0DBE  /* drive_sim, long */
#define D_radar_blink                            0x0DC4  /* drive_sim, int */
#define D_radar_dark                             0x0DC6  /* drive_scene, u16 */
#define D_radar_time                             0x0DC8  /* drive_scene, u32 */
#define D_palette_split_h                        0x0DCC  /* drive_scene, u16 */
#define D_cliff_x                                0x0DD2  /* drive_scene, s16 */
#define D_cliff_y                                0x0DD4  /* drive_scene, s16 */
#define D_cliff_scale                            0x0DD6  /* drive_scene, u16 */
#define D_min_row_y                              0x0DD8  /* drive_scene, s16 */
#define D_window_bottom                          0x0DDA  /* drive_scene, s16 */
#define D_prev_left                              0x0DDC  /* drive_scene, s16 */
#define D_prev_right                             0x0DDE  /* drive_scene, s16 */
#define D_prev_y                                 0x0DE0  /* drive_scene, s16 */
#define D_step_left                              0x0DE2  /* drive_scene, s16 */
#define D_step_right                             0x0DE4  /* drive_scene, s16 */
#define D_left_shoulder_x                        0x0DE6  /* drive_scene, s16[row+1] */
#define D_max_left_x                             0x0F78  /* drive_scene, s16 */
#define D_max_left_row                           0x0F7A  /* drive_scene, s16 */
#define D_shoulder_plane4                        0x0F7C  /* drive_scene, u16 */
#define D_mirror_flag                            0x0F7E  /* drive_scene, s16 */
#define D_queue_count                            0x0F80  /* drive_scene, s16 */
#define D_queue_x                                0x0F82  /* drive_scene, s16[199] */
#define D_queue_y                                0x1112  /* drive_scene, s16[199] */
#define D_queue_code                             0x12A2  /* drive_scene, s16[199] */
#define D_queue_scale                            0x1432  /* drive_scene, u16[199] */
#define D_traffic_size                           0x15C2  /* drive_scene, u16[14] stride 4 */
#define D_traffic_scale_tmp                      0x15FA  /* drive_scene, u16 */
#define D_police_flash                           0x15FC  /* drive_scene, u8 */
#define D_squeal_env                             0x15FE  /* drive_sim, int */
#define D_prev_gear                              0x1600  /* drive_sim, int */
#define D_prev_shifting                          0x1602  /* drive_sim, int */
#define D_overrev_frames                         0x1604  /* drive_sim, int */
#define D_drag_table                             0x1606  /* drive_sim, u8[64] */
#define D_crack_count                            0x1646  /* drive_scene, u16[7] */
#define D_crack_ptr                              0x1654  /* drive_scene, ptr[7] */
#define D_needle_rpm                             0x1900  /* drive_scene, u16 */
#define D_needle_speed                           0x1902  /* drive_scene, u16 */
#define D_gauge_pose                             0x1904  /* drive_scene, u16 */
#define D_digital_speed                          0x1906  /* drive_scene, u16[2] */
#define D_digital_rpm                            0x190A  /* drive_scene, u16[2] */
#define D_g_totalScore                           0x1910  /* game_flow, long */
#define D_fire_prev                              0x1916  /* drive_sim, int */
#define D_dir_prev                               0x1918  /* drive_sim, int */
#define D_rpm                                    0x191A  /* drive_sim, word+fraction */
#define D_gear                                   0x191E  /* drive_sim, int */
#define D_ratio                                  0x1920  /* drive_sim, int */
#define D_pedal                                  0x1922  /* drive_sim, int */
#define D_car_num_gears                          0x1924  /* drive_sim, int */
#define D_car_rev_limit                          0x1928  /* drive_sim, int */
#define D_car_grip                               0x192C  /* drive_sim, int */
#define D_car_skid_drift                         0x192E  /* drive_sim, int */
#define D_car_ratios                             0x1936  /* drive_sim, ptr */
#define D_car_knob_xy                            0x193A  /* drive_sim, ptr */
#define D_car_gate_xy                            0x193E  /* drive_sim, ptr */
#define D_car_gate_next                          0x1942  /* drive_sim, ptr */
#define D_car_node_gear                          0x1946  /* drive_sim, ptr */
#define D_car_torque                             0x194A  /* drive_sim, ptr */
#define D_stage_end                              0x1984  /* drive_sim, int */
#define D_road_stream                            0x1986  /* drive_sim, ptr */
#define D_road_records                           0x198A  /* drive_sim, ptr */
#define D_g_parTime                              0x198E  /* game_flow, long */
#define D_g_stageConstB                          0x1992  /* game_flow, long */
#define D_g_scoreFactor                          0x1996  /* game_flow, int */
#define D_marker_angle                           0x1998  /* drive_scene, s32 */
#define D_near_rows_flag                         0x199C  /* drive_scene, s16 */
#define D_marker_cache                           0x199E  /* drive_scene, s32 */
#define D_yaw_force                              0x19A2  /* drive_sim, long */
#define D_lat_force                              0x19A6  /* drive_sim, long 16.16 */
#define D_curve_acc                              0x19AA  /* drive_sim, long 16.16 */
#define D_car_x_new                              0x19AE  /* drive_sim, long */
#define D_lat_sign                               0x19B2  /* drive_sim, int */
#define D_view_yaw                               0x19B4  /* drive_sim, long 16.16 */
#define D_steer_track                            0x19B8  /* drive_sim, long 16.16 deg */
#define D_skid_amount                            0x19BC  /* drive_sim, int */
#define D_bump_edge                              0x19BE  /* drive_sim, int */
#define D_steer_prev                             0x19C4  /* drive_sim, long */
#define D_loading_palette                        0x19CA  /* drive_scene, u16[2] */
#define D_road_palette                           0x19CE  /* drive_scene, u16[32] */
#define D_hazard_table                           0x1A0E  /* drive_scene, Shape**[4] */
#define D_sign_table                             0x1A2E  /* drive_scene, Shape**[16] */
#define D_car_table                              0x1AAE  /* drive_scene, Shape**[16] */
#define D_mirror_car_table                       0x1B2E  /* drive_scene, Shape**[16] */
#define D_sfx_radar                              0x1BAE  /* platform_audio, sample* */
#define D_sfx_engine                             0x1BB2  /* platform_audio, sample* */
#define D_sfx_turbo                              0x1BB6  /* platform_audio, sample* */
#define D_sfx_squeal                             0x1BBA  /* platform_audio, sample* */
#define D_sfx_bump                               0x1BBE  /* platform_audio, sample* */
#define D_engine_period                          0x1BC2  /* platform_audio, int */
#define D_lzw_tables                             0x1BD2  /* platform_video, ptr */
#define D_rand_seed                              0x1BD6  /* platform_video, u16 */
#define D_rand_seeded                            0x1BD8  /* platform_video, int */
#define D_quit_flag                              0x1BDA  /* platform_video, int */
#define D_mem_list                               0x1BDC  /* platform_video, ptr */
#define D_mem_count                              0x1BE0  /* platform_video, int */
#define D__iob                                   0x1CDA  /* platform_video, FILE[] */
#define D__numdev                                0x1E92  /* platform_video, int */
#define D_g_fatalInit                            0x1E94  /* game_flow, int */
#define D_g_carsTxtPtr                           0x1E96  /* game_flow, char * */
#define D_sfx_server_a4                          0x1E9A  /* platform_audio, long */
#define D_sfx_int_channels                       0x1E9E  /* platform_audio, int */
#define D_sfx_vbl_interrupt                      0x1EA0  /* platform_audio, struct Interrupt */
#define D_song_server_a4                         0x1EB6  /* platform_audio, long */
#define D_song_vbl_interrupt                     0x1EBA  /* platform_audio, struct Interrupt */
#define D_song_inst_ptr                          0x1ED0  /* platform_audio, long[4] */
#define D_song_inst_owned                        0x1EE0  /* platform_audio, int[4] */
#define D_song_inst_oneshot                      0x1EE8  /* platform_audio, int[4] */
#define D_song_vol_step                          0x1EF0  /* platform_audio, long */
#define D_song_volume                            0x1EF4  /* platform_audio, long */
#define D_song_vol_target                        0x1EF8  /* platform_audio, long */
#define D_g_titleShapes                          0x1EFC  /* title_select, Shape *[43] */
#define D_out_count                              0x1FA8  /* platform_video, u32 */
#define D_unpacked_len                           0x1FB0  /* platform_video, u32 */
#define D_pack_inptr                             0x1FB4  /* platform_video, u8 * */
#define D_pack_outptr                            0x1FB8  /* platform_video, u8 * */
#define D_rle_state                              0x1FBC  /* platform_video, int */
#define D_packed_left                            0x1FBE  /* platform_video, u32 */
#define D_rle_last                               0x23EC  /* platform_video, int */
#define D_key_code                               0x23EE  /* platform_video, u8[10] */
#define D_key_qual                               0x23F8  /* platform_video, u16[10] */
#define D_key_count                              0x240C  /* platform_video, int */
#define D_key_max                                0x240E  /* platform_video, int */
#define D_input_port                             0x2410  /* platform_video, MsgPort * */
#define D_con_port                               0x2414  /* platform_video, MsgPort * */
#define D_input_io                               0x2418  /* platform_video, IOStdReq * */
#define D_input_irq                              0x241C  /* platform_video, Interrupt */
#define D_con_io                                 0x2482  /* platform_video, IOStdReq * */
#define D_key_pass_qual                          0x2486  /* platform_video, u16 */
#define D__malloc_list                           0x24A8  /* platform_video, ptr */
#define D_Enable_Abort                           0x24AC  /* platform_video, int */
#define D_drawer_pause                           0x24AE  /* drive_scene, u16 */
#define D_gate_mode                              0x24B0  /* drive_sim, int */
#define D_knob_target_y                          0x24B2  /* drive_sim, int */
#define D_knob_y                                 0x24B4  /* drive_sim, int */
#define D_knob_target_x                          0x24B6  /* drive_sim, int */
#define D_knob_x                                 0x24B8  /* drive_sim, int */
#define D_gearbox_hide_delay                     0x24BA  /* drive_sim, int */
#define D_g_loadedBuf                            0x24BC  /* platform_video, ptr */
#define D_g_frontRastPort                        0x24C0  /* title_select, RastPort * */
#define D_g_tooSlow                              0x24C4  /* game_flow, int */
#define D_g_lives                                0x24C6  /* game_flow, int */
#define D_g_backView                             0x24C8  /* title_select, View * */
#define D_g_stage                                0x24CC  /* game_flow, int */
#define D_g_frontView                            0x24CE  /* title_select, View * */
#define D_dash_palette                           0x24D2  /* drive_scene, u16[32] */
#define D_g_joyDir                               0x2512  /* platform_video, int */
#define D_g_carRecord                            0x2548  /* game_flow, void * */
#define D_shifting                               0x26FC  /* drive_sim, int */
#define D_tach_overlay                           0x2726  /* drive_scene, Shape* */
#define D_speed_overlay                          0x272A  /* drive_scene, Shape* */
#define D_tach_overlay_mask                      0x2756  /* drive_scene, Shape* */
#define D_speed_overlay_mask                     0x275A  /* drive_scene, Shape* */
#define D_spr_govr                               0x2766  /* game_flow, Shape * */
#define D_spr_gvrm                               0x276A  /* game_flow, Shape * */
#define D_mask_pool                              0x276E  /* drive_scene, ptr */
#define D_dash_shapes                            0x27CE  /* drive_scene, ptr */
#define D_road_shapes                            0x27D2  /* drive_scene, ptr */
#define D_errno                                  0x27D6  /* platform_video, int */
#define D__initial_sp                            0x27D8  /* platform_video, ptr */
#define D_SysBase                                0x27DC  /* platform_video, ptr */
#define D_DOSBase                                0x27E0  /* platform_video, ptr */
#define D__devtab                                0x27E4  /* platform_video, ptr */
#define D__argv                                  0x27F0  /* platform_video, char ** */
#define D__argc                                  0x27F4  /* platform_video, int */
#define D_g_loadedSize                           0x2810  /* platform_video, long */
#define D_g_inGame                               0x2814  /* game_flow, int */
#define D_demo_mode                              0x2816  /* game_flow, int */
#define D_saved_task_pri                         0x2818  /* platform_video, int */
#define D_g_selectedCar                          0x281A  /* game_flow, int */
#define D_saved_bltpri                           0x281C  /* platform_video, int */
#define D_cmp2_line                              0x281E  /* platform_video, int */
#define D_g_scrollDelay                          0x2820  /* game_flow, int */
#define D_g_quitSeen                             0x2822  /* game_flow, int */
#define D_g_scrollerDone                         0x2824  /* title_select, int */
#define D_crash                                  0x282E  /* drive_sim, int */
#define D_no_crash                               0x2830  /* drive_sim, int */
#define D_knob_shown_x                           0x2832  /* drive_scene, s16 */
#define D_knob_shown_y                           0x2834  /* drive_scene, s16 */
#define D_back_index                             0x2836  /* drive_scene, u16 */
#define D_pitch_bump_flag                        0x283C  /* drive_scene, s16 */
#define D_sprite_shake                           0x2840  /* drive_scene, s16 */
#define D_horizon_shake                          0x2842  /* drive_scene, s16 */
#define D_drawer_paused_ack                      0x2844  /* drive_scene, u16 */
#define D_dash_palette_valid                     0x2846  /* drive_scene, u16 */
#define D_sd_enable                              0x2848  /* drive_sim, int */
#define D_on_enable                              0x284A  /* drive_sim, int */
#define D_knob_visible                           0x284C  /* drive_scene, u16 */
#define D_needle_seg                             0x284E  /* drive_scene, u16 */
#define D_dot_seg                                0x2850  /* drive_scene, u16 */
#define D_speed_pair_shift                       0x2852  /* drive_scene, u16 */
#define D_tach_pair_shift                        0x2854  /* drive_scene, u16 */
#define D_g_joyFire                              0x2858  /* platform_video, int */
#define D_saved_windowptr                        0x285A  /* platform_video, long */
#define D_this_task                              0x285E  /* platform_video, Task * */
#define D_saved_task_2A                          0x2862  /* platform_video, long */
#define D_saved_actiview                         0x2866  /* platform_video, View * */
#define D_colormapA                              0x286A  /* platform_video, ColorMap * */
#define D_colormapB                              0x286E  /* platform_video, ColorMap * */
#define D_text_font                              0x2872  /* platform_video, TextFont * */
#define D_g_tmpRastPort                          0x2876  /* platform_video, RastPort * */
#define D_g_backRastPort                         0x287A  /* title_select, RastPort * */
#define D_g_scrollerStack                        0x287E  /* title_select, void * */
#define D_g_scrollerTask                         0x2882  /* title_select, struct Task * */
#define D_g_scrollerView                         0x2886  /* title_select, View * */
#define D_g_scrollerFunc                         0x288A  /* title_select, void (*)(View *) */
#define D_g_sheetCmA                             0x288E  /* title_select, ColorMap * */
#define D_g_sheetCmB                             0x2892  /* title_select, ColorMap * */
#define D_car_x                                  0x2896  /* drive_sim, long 16.16 */
#define D_r_lateral                              0x289A  /* drive_scene, s32 */
#define D_r_speed                                0x289E  /* drive_scene, s32 */
#define D_r_steer                                0x28A2  /* drive_scene, s32 */
#define D_speed                                  0x28A6  /* drive_sim, long 16.16 mph */
#define D_steer                                  0x28AA  /* drive_sim, long 16.16 deg */
#define D_road_pos                               0x28AE  /* drive_sim, long 16.16 units */
#define D_advance                                0x28B6  /* drive_sim, long 16.16 units */
#define D_r_road_pos                             0x28BA  /* drive_scene, s32 */
#define D_heading                                0x28C6  /* drive_sim, long 16.16 deg */
#define D_pitch_acc                              0x28CA  /* drive_sim, long */
#define D_road_pos_done                          0x28CE  /* drive_sim, long */
#define D_drawer_frames                          0x28D6  /* drive_scene, u32 */
#define D_needle_shape                           0x28DA  /* drive_scene, ptr */
#define D_needle_rp                              0x28DE  /* drive_scene, RastPort* */
#define D_needle_bm                              0x28E2  /* drive_scene, BitMap* */
#define D_drawer_stack                           0x28E6  /* drive_scene, ptr */
#define D_drawer_task                            0x28EA  /* drive_scene, Task* */
#define D_ConsoleDevice                          0x28EE  /* platform_video, ptr */
#define D_IconBase                               0x28F2  /* platform_video, ptr */
#define D_knob_seg                               0x28F6  /* drive_scene, u16[4] */
#define D_rasinfoA                               0x28FE  /* platform_video, RasInfo */
#define D_rasinfoB                               0x290A  /* platform_video, RasInfo */
#define D_g_sheetRasA                            0x2916  /* title_select, struct RasInfo */
#define D_g_sheetRasB                            0x2922  /* title_select, struct RasInfo */
#define D_sprite_next_word                       0x292E  /* drive_scene, u16[8] */
#define D_g_viewA                                0x293E  /* title_select, struct View (0x12) */
#define D_g_viewB                                0x2950  /* title_select, struct View (0x12) */
#define D_vbl_irq                                0x2E12  /* platform_video, Interrupt */
#define D_song_name                              0x2E28  /* platform_audio, char[] */
#define D_sprite_data                            0x2E46  /* drive_scene, u16*[8] */
#define D_g_carNames                             0x2E66  /* game_flow, char *[] */
#define D_g_vpA                                  0x2E8E  /* title_select, struct ViewPort (0x28) */
#define D_g_vpA_DHeight                          0x2EA8  /* title_select, int */
#define D_g_vpA_DxOffset                         0x2EAA  /* title_select, int */
#define D_g_vpA_DyOffset                         0x2EAC  /* title_select, int */
#define D_g_vpB                                  0x2EB6  /* title_select, struct ViewPort (0x28) */
#define D_g_vpB_DHeight                          0x2ED0  /* title_select, int */
#define D_g_vpB_DxOffset                         0x2ED2  /* title_select, int */
#define D_g_vpB_DyOffset                         0x2ED4  /* title_select, int */
#define D_g_bitmapA                              0x2EDE  /* title_select, struct BitMap (0x28) */
#define D_g_bitmapB                              0x2F06  /* title_select, struct BitMap (0x28) */
#define D_g_sheetVpA                             0x2F2E  /* title_select, struct ViewPort (0x28) */
#define D_g_sheetVpB                             0x2F56  /* title_select, struct ViewPort (0x28) */
#define D_g_sheetBmA                             0x2F7E  /* title_select, struct BitMap (0x28) */
#define D_g_sheetBmB                             0x2FA6  /* title_select, struct BitMap (0x28) */
#define D_cmp2_palette                           0x2FCE  /* platform_video, u16[32] */
#define D_g_stCache                              0x300E  /* title_select, void *[20] */
#define D_g_sbCache                              0x305E  /* title_select, void *[20] */
#define D_g_rpA                                  0x30AE  /* title_select, struct RastPort (0x64) */
#define D_g_rpB                                  0x3112  /* title_select, struct RastPort (0x64) */
#define D_g_resultsRastPort                      0x3176  /* game_flow, struct RastPort */
#define D_g_sheetRpA                             0x31DA  /* title_select, struct RastPort */
#define D_g_sheetRpB                             0x323E  /* title_select, struct RastPort */

/* Original functions (image addresses) */
#define FN_main                                  0x10018  /* game_flow, int main(int argc char **argv) */
#define FN_close_workbench                       0x1032C  /* platform_video, void (void) */
#define FN_load_cars_txt                         0x10346  /* game_flow, void(int load) */
#define FN_skip_line                             0x10402  /* game_flow, char *(char **pp) */
#define FN_blit_priority_on                      0x1042E  /* platform_video, void (void) */
#define FN_blit_priority_off                     0x1044C  /* platform_video, void (void) */
#define FN_poll_input                            0x10462  /* platform_video, void (void) */
#define FN_protection_check                      0x10588  /* platform_video, void (void) */
#define FN_nop_10632                             0x10632  /* platform_video, void (void) */
#define FN_ilbm_to_view                          0x1063A  /* platform_video, void (u8 *iff, View *v) */
#define FN_iff_next_chunk                        0x10692  /* platform_video, void (u8 *base, long *off) */
#define FN_ilbm_parse                            0x106BE  /* platform_video, void (u8 *form, View *v) */
#define FN_cmap_to_rgb4                          0x107B4  /* platform_video, void (u8 *chunk, u16 pal[32]) */
#define FN_cmp2_to_rgb4                          0x1086E  /* platform_video, void (u8 *chunk) */
#define FN_ilbm_decode_body                      0x10906  /* platform_video, void (BMHD *h, u16 *pal, u8 *body, View  */
#define FN_view_dissolve                         0x109D0  /* platform_video, void (View *src_or_NULL, View *dst) */
#define FN_dissolve_pass                         0x10AA2  /* platform_video, void (int k, int depth, u8 **src, u8 **d */
#define FN_res_find_list                         0x10B22  /* title_select, void(Archive *a long *names Shape **out  */
#define FN_arena_new                             0x10BA8  /* platform_video, Arena *(long size) */
#define FN_arena_alloc                           0x10BDC  /* platform_video, void *(Arena *a, long n) */
#define FN_arena_free_bytes                      0x10C28  /* platform_video, long (Arena *a) */
#define FN_mask_size                             0x10C3E  /* platform_video, long (Shape *s) */
#define FN_make_mask                             0x10C5A  /* platform_video, Shape *(Arena *a, Shape *s) */
#define FN_empty_hook                            0x10CEC  /* game_flow, void(void) */
#define FN_nop_10cf4                             0x10CF4  /* platform_video, void (void) */
#define FN_nop_10d04                             0x10D04  /* platform_video, void (void) */
#define FN_blit_begin                            0x10D14  /* platform_video, void (void) */
#define FN_blit_nasty_off                        0x10D3C  /* platform_video, asm */
#define FN_blit_wait_hw                          0x10D44  /* platform_video, asm A6=$DFF000 */
#define FN_read_dmaconr                          0x10D66  /* platform_video, u16 (void) */
#define FN_blit_clear_rect                       0x10D72  /* platform_video, asm a0 plane d0 x d1 y d2 wbytes d3 h */
#define FN_blit_fill_rect                        0x10DBE  /* platform_video, asm a0 plane d0 x d1 y d2 wbytes d3 h */
#define FN_shape_pos                             0x10E12  /* platform_video, asm a0 shape -> d0,d1 */
#define FN_shape_sub_hot                         0x10E1C  /* platform_video, asm */
#define FN_blit_set_dest                         0x10E26  /* platform_video, void (u8 *planes[5]) */
#define FN_blit_shape_word                       0x10E3A  /* platform_video, void (Shape *s, Shape *mask, int x, int  */
#define FN_blit_shape                            0x10E58  /* platform_video, void (Shape *s, Shape *mask, int x, int  */
#define FN_blit_wait                             0x10E78  /* platform_video, void (void) */
#define FN_blit_shape_word_asm                   0x10E88  /* platform_video, asm a0 s a1 mask d0 x d1 y */
#define FN_blit_params_ptr                       0x10F9C  /* platform_video, asm -> &D:0362 */
#define FN_set_clip_full                         0x10FA4  /* platform_video, void (void) */
#define FN_set_clip                              0x10FBC  /* platform_video, asm d0 top d1 bottom d2 left d3 right */
#define FN_blit_prep_word                        0x10FDA  /* platform_video, asm -> C set if nothing */
#define FN_blit_shape_asm                        0x110C4  /* platform_video, asm a0 s a1 mask d0 x d1 y */
#define FN_blit_shape_xor                        0x111E6  /* platform_video, asm a0 s d0 x d1 y */
#define FN_blit_prep_shift                       0x112E4  /* platform_video, asm -> C set if nothing */
#define FN_blit_shape_xor_word                   0x11432  /* platform_video, asm a0 s d0 x d1 y */
#define FN_open_libraries                        0x11554  /* platform_video, void (void) */
#define FN_close_libraries                       0x115A0  /* platform_video, void (void) */
#define FN_display_init                          0x115BC  /* platform_video, void (void) */
#define FN_display_shutdown                      0x11756  /* platform_video, void (void) */
#define FN_set_task_pri                          0x117E8  /* platform_video, int (int pri) */
#define FN_vbl_install                           0x1180E  /* platform_video, void (void) */
#define FN_vbl_remove                            0x1185C  /* platform_video, void (void) */
#define FN_read_fire_raw                         0x11872  /* platform_video, asm -> d0 */
#define FN_read_joy_raw                          0x11886  /* platform_video, asm -> d0 */
#define FN_vbl_server                            0x118B2  /* platform_video, interrupt server (A1=&D:03D8) */
#define FN_prot_measure_setup                    0x11954  /* platform_video, int (char *volname) */
#define FN_prot_code_len                         0x119B6  /* platform_video, long (void) */
#define FN_prot_code_start                       0x119D0  /* platform_video, void *(void) */
#define FN_prot_cleanup                          0x119D8  /* platform_video, void (void) */
#define FN_prot_read_track                       0x11A0A  /* platform_video, int (long cyl, long head) */
#define FN_prot_measure_gap                      0x11D3A  /* platform_video, asm */
#define FN_prot_crc                              0x11D8E  /* platform_video, u16 (void *p, long nwords, long init, lo */
#define FN_prot_crc_core                         0x11DB0  /* platform_video, asm */
#define FN_lmul_signed                           0x11F52  /* platform_video, asm d0 d1 -> d0 */
#define FN_fix_mul                               0x11F94  /* platform_video, asm d0 d1 -> d0 */
#define FN_fix_div                               0x11FD6  /* platform_video, asm d0.w d1.w -> d0 */
#define FN_isqrt                                 0x1200E  /* platform_video, asm d0 -> d0.w */
#define FN_abs16                                 0x12056  /* platform_video, asm */
#define FN_abs32                                 0x1205E  /* platform_video, asm */
#define FN_ltoa_dec                              0x12066  /* platform_video, asm d0 -> a0 */
#define FN_sin_deg_fix                           0x12108  /* platform_video, asm d0 16.16 deg -> d0 */
#define FN_cos_deg                               0x12146  /* platform_video, asm d0.w -> d0.w */
#define FN_tan_deg_fix                           0x12224  /* platform_video, asm d0.w -> d0 */
#define FN_sfx_init                              0x12304  /* platform_audio, void(void) */
#define FN_sfx_shutdown                          0x123EC  /* platform_audio, void(void) */
#define FN_sfx_set_song_channels                 0x12432  /* platform_audio, void(int mask) */
#define FN_play_sample                           0x1246A  /* platform_audio, void(sample *s, int ch, int vol) */
#define FN_start_channel                         0x124C4  /* platform_audio, void(u8 *data, long len, int ch, int per */
#define FN_snd_stop_all                          0x1252A  /* platform_audio, void(void) */
#define FN_sfx_stop_channel                      0x12546  /* platform_audio, void(int ch) */
#define FN_sfx_channel_busy                      0x1258E  /* platform_audio, int(int ch) */
#define FN_sfx_set_period_vol                    0x125A6  /* platform_audio, void(int ch, int period, int vol) */
#define FN_sfx_slide_volume                      0x125F4  /* platform_audio, void(int ch, int target, long step) */
#define FN_sfx_audio_int                         0x12616  /* platform_audio, level-4 autovector handler */
#define FN_sfx_vbl_server                        0x126AE  /* platform_audio, VERTB interrupt server */
#define FN_song_init                             0x1278C  /* platform_audio, void(void) */
#define FN_song_shutdown                         0x127F4  /* platform_audio, void(void) */
#define FN_song_load_instruments                 0x12826  /* platform_audio, void(char *names[4], int oneshot[4]) */
#define FN_song_free_instruments                 0x128FE  /* platform_audio, void(void) */
#define FN_song_set_volume                       0x12942  /* platform_audio, void(int vol, long step) */
#define FN_song_get_volume                       0x1295E  /* platform_audio, int(void) */
#define FN_song_start                            0x12972  /* platform_audio, void(u8 *smus) */
#define FN_song_request_stop                     0x1299C  /* platform_audio, asm */
#define FN_song_setup                            0x129BA  /* platform_audio, asm (a0 song, a1 inst[4], a2 oneshot[4], */
#define FN_song_is_active                        0x12A40  /* platform_audio, int(void) */
#define FN_song_vbl_server                       0x12A54  /* platform_audio, VERTB interrupt server */
#define FN_song_volume_slide                     0x12C98  /* platform_audio, asm */
#define FN_smus_find_long                        0x12CDC  /* platform_audio, asm (a0 base d0 off d1 limit d2 id) */
#define FN_song_play                             0x12CF4  /* platform_audio, void(char *file, char *inst[4], int ones */
#define FN_song_stop                             0x12DB0  /* platform_audio, void(void) */
#define FN_song_play_testdrive                   0x12E12  /* platform_audio, void(void) */
#define FN_song_play_test2                       0x12E58  /* platform_audio, void(void) */
#define FN_song_play_testgas                     0x12E8A  /* platform_audio, void(void) */
#define FN_song_play_endsuccess                  0x12EBE  /* platform_audio, void(void) */
#define FN_song_play_loser                       0x12EF6  /* platform_audio, void(void) */
#define FN_high_scores                           0x12F28  /* game_flow, int(long score int car) */
#define FN_read_line                             0x12FF0  /* game_flow, char *(char *dst char *src) */
#define FN_scores_load                           0x13028  /* game_flow, int(char names[8][40] long scores[8] cha */
#define FN_scores_save                           0x1313E  /* game_flow, void(char names[8][40] long scores[8] ch */
#define FN_text_init                             0x13250  /* platform_video, void (void) */
#define FN_text_shutdown                         0x132E6  /* platform_video, void (void) */
#define FN_text_print                            0x13306  /* platform_video, void (char *s) */
#define FN_text_move                             0x13330  /* platform_video, void (int x, int y) */
#define FN_text_set_pen                          0x13354  /* platform_video, void (int c) */
#define FN_draw_box_outline                      0x1336E  /* platform_video, void (int x0, int y0, int x1, int y1) */
#define FN_erase_rect                            0x1343A  /* platform_video, void (int x0, int y0, int x1, int y1) */
#define FN_text_cursor                           0x134F2  /* platform_video, void (void) */
#define FN_text_input_line                       0x135B4  /* game_flow, void(char *buf int maxlen) */
#define FN_scores_enter_name                     0x13708  /* game_flow, void(long score int car char names[8][40 */
#define FN_credits_show                          0x13A9E  /* game_flow, int(void) */
#define FN_scores_show                           0x13BD8  /* game_flow, int(char names[8][40] long scores[8] cha */
#define FN_hs_draw_logo                          0x13E86  /* game_flow, void(int row char *carPath) */
#define FN_hs_logo_palette                       0x13F32  /* game_flow, void(int row char *carPath UCopList *ucl */
#define FN_crc16                                 0x1406E  /* game_flow, uint(void *buf long len uint init uint p */
#define FN_crc16_core                            0x14088  /* game_flow, asm a0 d1 d0 d2 */
#define FN_wait_vbl_or_fire                      0x1433A  /* game_flow, void(int n) */
#define FN_quit_sticky                           0x1436E  /* game_flow, int(void) */
#define FN_results_add_line                      0x14388  /* game_flow, void(char *s) */
#define FN_results_text                          0x1444C  /* game_flow, void(long avgSpeed int secs long score i */
#define FN_stage_results                         0x147E4  /* game_flow, void(int car long avgSpeed int secs long */
#define FN_draw_shape_on_view                    0x14984  /* platform_video, void (Shape *s, View *v) */
#define FN_load_file                             0x149D2  /* platform_video, void *(char *name) */
#define FN_load_file_chip                        0x149E8  /* platform_video, void *(char *name) */
#define FN_load_file_flags                       0x149FE  /* platform_video, void *(char *name, long flags) */
#define FN_pckd_unpacked_len                     0x14C8C  /* platform_video, long (u8 *hdr) */
#define FN_pckd_unpack                           0x14C9C  /* platform_video, void (u8 *pckd, u8 *out) */
#define FN_huff_read_tree                        0x14D64  /* platform_video, void (void) */
#define FN_huff_read_word                        0x14DC6  /* platform_video, int (void) */
#define FN_huff_decode                           0x14DE0  /* platform_video, int (void) */
#define FN_rle90_out                             0x14E6C  /* platform_video, void (u8 c) */
#define FN_pack_getc                             0x14ED6  /* platform_video, int (void) */
#define FN_pack_putc                             0x14EF2  /* platform_video, void (u8 c) */
#define FN_lzw_decompress                        0x14F0E  /* platform_video, void (void) */
#define FN_lzw_getcode                           0x1506C  /* platform_video, int (void) */
#define FN_lzw_alloc_tables                      0x15192  /* platform_video, void (void) */
#define FN_lzw_free_tables                       0x151D6  /* platform_video, void (void) */
#define FN_load_raw                              0x151F2  /* platform_video, void *(char *name) */
#define FN_load_raw_chip                         0x15208  /* platform_video, void *(char *name) */
#define FN_load_raw_flags                        0x1521E  /* platform_video, void *(char *name, long flags) */
#define FN_rand16                                0x1530E  /* platform_video, int (void) */
#define FN_unpack_byterun1_row                   0x15344  /* platform_video, void (u8 **src, u8 **dst, int n) */
#define FN_fire_port_init                        0x153CC  /* platform_video, void (void) */
#define FN_joy_fire                              0x153E4  /* platform_video, int (void) */
#define FN_joy_dir                               0x153EC  /* platform_video, int (void) */
#define FN_joy_read_both                         0x153F4  /* platform_video, asm */
#define FN_read_fire                             0x15402  /* platform_video, asm -> d0 */
#define FN_read_joy                              0x15416  /* platform_video, asm -> d0 */
#define FN_quit_requested                        0x1544E  /* platform_video, int (void) */
#define FN_find_shape                            0x15472  /* platform_video, Shape *(Archive *a, long name4) */
#define FN_find_shape_asm                        0x15490  /* platform_video, asm a0 d0 -> a0 */
#define FN_input_init                            0x154E4  /* platform_video, void (int passmask) */
#define FN_input_shutdown                        0x155C4  /* platform_video, void (void) */
#define FN_get_char                              0x15628  /* platform_video, int (void) */
#define FN_key_to_ascii                          0x1563A  /* platform_video, int (long qual_code) */
#define FN_input_handler                         0x15698  /* platform_video, InputEvent *(InputEvent *) */
#define FN_key_available                         0x156EC  /* platform_video, asm -> d0 */
#define FN_get_key                               0x156F8  /* platform_video, long (void) */
#define FN_view_clear                            0x1574E  /* platform_video, void (View *v) */
#define FN_view_copy                             0x1580C  /* platform_video, void (View *src, View *dst) */
#define FN_view_copy_palette                     0x1582C  /* platform_video, void (View *src, View *dst) */
#define FN_view_copy_bitmaps                     0x1587C  /* platform_video, void (View *src, View *dst) */
#define FN_alloc_public                          0x15904  /* platform_video, void *(long size) */
#define FN_alloc_chip                            0x1591A  /* platform_video, void *(long size) */
#define FN_mem_alloc                             0x15930  /* platform_video, void *(long size, long flags) */
#define FN_free_mem                              0x159FA  /* platform_video, int (void *p) */
#define FN_mem_check                             0x15B3E  /* platform_video, int (void *p) */
#define FN_mem_size                              0x15C60  /* platform_video, long (void *p) */
#define FN_raw_putc                              0x15CAC  /* platform_video, asm */
#define FN_kprintf                               0x15CE8  /* platform_video, void (char *fmt, ...) */
#define FN_raw_dofmt                             0x15CFC  /* platform_video, asm */
#define FN_toupper                               0x15D1C  /* platform_video, int (int c) */
#define FN_tolower                               0x15D34  /* platform_video, int (int c) */
#define FN_sscanf                                0x15D4C  /* platform_video, int (char *s, char *fmt, ...) */
#define FN__sscanf_getc                          0x15D72  /* platform_video, int (int unget) */
#define FN__scanfmt                              0x15DBC  /* platform_video, int (fn getc, char *fmt, void **args) */
#define FN__scan_skipws                          0x160E0  /* platform_video, int (void) */
#define FN__scan_int                             0x1611A  /* platform_video, int (...) */
#define FN_fopen                                 0x1620C  /* platform_video, FILE *(char *name, char *mode) */
#define FN__openstream                           0x16236  /* platform_video, FILE *(char *name, char *mode, FILE *fp) */
#define FN_fprintf                               0x162A8  /* platform_video, int (FILE *fp, char *fmt, ...) */
#define FN__fprintf_putc                         0x162CA  /* platform_video, void (int c) */
#define FN_ovl_unload                            0x162E0  /* platform_video, void (void *stub) */
#define FN_strchr                                0x16396  /* platform_video, char *(char *s, int c) */
#define FN__start                                0x163B0  /* platform_video, entry */
#define FN__stub_init                            0x16422  /* platform_video, void (void) */
#define FN__main                                 0x1642A  /* platform_video, void (long alen, char *aptr) */
#define FN__cli_parse                            0x16566  /* platform_video, void (...) */
#define FN_strncpy                               0x1670C  /* platform_video, char *(char *d, char *s, int n) */
#define FN_creat                                 0x1672E  /* platform_video, int (char *name, int mode) */
#define FN_open                                  0x16746  /* platform_video, int (char *name, int flags) */
#define FN_ovl_load                              0x168A4  /* platform_video, overlay supervisor */
#define FN_ovl_loadseg                           0x1691C  /* platform_video, asm */
#define FN_strcat                                0x16986  /* platform_video, char *(char *d, char *s) */
#define FN_strncat                               0x1698C  /* platform_video, char *(char *d, char *s, int n) */
#define FN_strcmp                                0x169B0  /* platform_video, int (char *a, char *b) */
#define FN_strncmp                               0x169B6  /* platform_video, int (char *a, char *b, int n) */
#define FN_strcpy                                0x169E0  /* platform_video, char *(char *d, char *s) */
#define FN__lmul                                 0x169F0  /* platform_video, asm d0 d1 -> d0 */
#define FN__wb_parse                             0x16A14  /* platform_video, void (Process *p, WBStartup *msg) */
#define FN_sprintf                               0x16AC8  /* platform_video, int (char *buf, char *fmt, ...) */
#define FN__sprintf_putc                         0x16AF8  /* platform_video, int (int c) */
#define FN_printf                                0x16B14  /* platform_video, int (char *fmt, ...) */
#define FN__fmt_number                           0x16B30  /* platform_video, char *(void *v, int sign, char *end, int */
#define FN__format                               0x16BBE  /* platform_video, int (fn putc, char *fmt, void *args) */
#define FN__divs32                               0x16ED8  /* platform_video, asm d0/d1 -> d0 */
#define FN__modu32                               0x16F1A  /* platform_video, asm */
#define FN__divu32                               0x16F26  /* platform_video, asm */
#define FN__udiv_core                            0x16F30  /* platform_video, asm */
#define FN_strlen                                0x16F80  /* platform_video, int (char *s) */
#define FN__printf_putc                          0x16F92  /* platform_video, void (int c) */
#define FN_putc                                  0x16FA8  /* platform_video, int (int c, FILE *fp) */
#define FN__putc                                 0x16FEA  /* platform_video, int (int c, FILE *fp) */
#define FN__flushall                             0x17026  /* platform_video, void (void) */
#define FN_fclose                                0x1704E  /* platform_video, int (FILE *fp) */
#define FN__flsbuf                               0x170D4  /* platform_video, int (FILE *fp, int c) */
#define FN__getstream                            0x171B6  /* platform_video, FILE *(void) */
#define FN__getbuf                               0x171EE  /* platform_video, void (FILE *fp) */
#define FN__freeall                              0x1724C  /* platform_video, void (void) */
#define FN_malloc                                0x1727E  /* platform_video, void *(unsigned long n) */
#define FN__malloc16                             0x172BE  /* platform_video, void *(unsigned n) */
#define FN_free                                  0x172D2  /* platform_video, int (void *p) */
#define FN_isatty                                0x1731E  /* platform_video, int (int fd) */
#define FN_unlink                                0x17376  /* platform_video, int (char *name) */
#define FN_write                                 0x1739A  /* platform_video, int (int fd, void *buf, unsigned n) */
#define FN_Chk_Abort                             0x17418  /* platform_video, long (void) */
#define FN__abort                                0x17448  /* platform_video, void (void) */
#define FN_exit                                  0x17474  /* platform_video, void (int code) */
#define FN__exit                                 0x17492  /* platform_video, void (int code) */
#define FN_close                                 0x17580  /* platform_video, int (int fd) */
#define FN_dos_Close                             0x175CE  /* platform_video, library glue */
#define FN_dos_Close_body                        0x175D2  /* platform_video, library glue */
#define FN_dos_CurrentDir                        0x175DE  /* platform_video, library glue */
#define FN_dos_Delay                             0x175EA  /* platform_video, library glue */
#define FN_dos_DeleteFile                        0x175F6  /* platform_video, library glue */
#define FN_dos_Examine                           0x17602  /* platform_video, library glue */
#define FN_dos_Examine_body                      0x17606  /* platform_video, library glue */
#define FN_dos_Input                             0x17614  /* platform_video, library glue */
#define FN_dos_IoErr                             0x1761C  /* platform_video, library glue */
#define FN_dos_IsInteractive                     0x17624  /* platform_video, library glue */
#define FN_dos_Lock                              0x17630  /* platform_video, library glue */
#define FN_dos_Lock_body                         0x17634  /* platform_video, library glue */
#define FN_dos_Open                              0x17642  /* platform_video, library glue */
#define FN_dos_Open_body                         0x17646  /* platform_video, library glue */
#define FN_dos_Output                            0x17654  /* platform_video, library glue */
#define FN_dos_Read                              0x1765C  /* platform_video, library glue */
#define FN_dos_Read_body                         0x17660  /* platform_video, library glue */
#define FN_dos_Seek                              0x1766E  /* platform_video, library glue */
#define FN_dos_UnLock                            0x1767C  /* platform_video, library glue */
#define FN_dos_UnLock_body                       0x17680  /* platform_video, library glue */
#define FN_dos_Write                             0x1768C  /* platform_video, library glue */
#define FN_exec_AddIntServer                     0x1769A  /* platform_video, library glue */
#define FN_exec_Alert                            0x176A8  /* platform_video, library glue */
#define FN_exec_CloseDevice                      0x176C0  /* platform_video, library glue */
#define FN_exec_CloseLibrary                     0x176CC  /* platform_video, library glue */
#define FN_exec_CloseLibrary_body                0x176D0  /* platform_video, library glue */
#define FN_exec_CopyMemQuick                     0x176DC  /* platform_video, library glue */
#define FN_CreatePort                            0x176EE  /* platform_video, library glue */
#define FN_DeletePort                            0x1777A  /* platform_video, library glue */
#define FN_exec_AddPort                          0x177C0  /* platform_video, library glue */
#define FN_exec_AllocSignal                      0x177CC  /* platform_video, library glue */
#define FN_CreateStdIO                           0x177D8  /* platform_video, library glue */
#define FN_DeleteStdIO                           0x177EE  /* platform_video, library glue */
#define FN_CreateExtIO                           0x17800  /* platform_video, library glue */
#define FN_DeleteExtIO                           0x17844  /* platform_video, library glue */
#define FN_exec_AllocMem                         0x17880  /* platform_video, library glue */
#define FN_exec_AllocMem_body                    0x17884  /* platform_video, library glue */
#define FN_exec_AddTask                          0x17892  /* platform_video, library glue */
#define FN_exec_DoIO                             0x178AA  /* platform_video, library glue */
#define FN_exec_FindTask                         0x178C0  /* platform_video, library glue */
#define FN_exec_FindTask_body                    0x178C4  /* platform_video, library glue */
#define FN_exec_Forbid                           0x178D0  /* platform_video, library glue */
#define FN_exec_Forbid_body                      0x178D4  /* platform_video, library glue */
#define FN_exec_FreeMem                          0x178DC  /* platform_video, library glue */
#define FN_exec_FreeMem_body                     0x178E0  /* platform_video, library glue */
#define FN_exec_FreeSignal                       0x178F0  /* platform_video, library glue */
#define FN_exec_GetMsg                           0x178FC  /* platform_video, library glue */
#define FN_NewList                               0x17908  /* platform_video, library glue */
#define FN_exec_OpenDevice                       0x1791A  /* platform_video, library glue */
#define FN_exec_OpenLibrary                      0x17930  /* platform_video, library glue */
#define FN_exec_OpenLibrary_body                 0x17934  /* platform_video, library glue */
#define FN_exec_Permit                           0x17944  /* platform_video, library glue */
#define FN_exec_RemIntServer                     0x1794C  /* platform_video, library glue */
#define FN_exec_RemPort                          0x1795A  /* platform_video, library glue */
#define FN_exec_RemTask                          0x17966  /* platform_video, library glue */
#define FN_exec_ReplyMsg                         0x17972  /* platform_video, library glue */
#define FN_exec_SetSignal                        0x1797E  /* platform_video, library glue */
#define FN_exec_SetTaskPri                       0x1798C  /* platform_video, library glue */
#define FN_exec_WaitPort                         0x1799C  /* platform_video, library glue */
#define FN_gfx_BltBitMap                         0x179A8  /* platform_video, library glue */
#define FN_gfx_BltClear                          0x179CA  /* platform_video, library glue */
#define FN_gfx_CBump                             0x179DC  /* platform_video, library glue */
#define FN_gfx_CloseFont                         0x179E8  /* platform_video, library glue */
#define FN_gfx_CMove                             0x179F4  /* platform_video, library glue */
#define FN_gfx_CWait                             0x17A06  /* platform_video, library glue */
#define FN_gfx_DisownBlitter                     0x17A18  /* platform_video, library glue */
#define FN_gfx_Draw                              0x17A20  /* platform_video, library glue */
#define FN_gfx_FreeColorMap                      0x17A32  /* platform_video, library glue */
#define FN_gfx_FreeCprList                       0x17A3E  /* platform_video, library glue */
#define FN_gfx_FreeVPortCopLists                 0x17A4A  /* platform_video, library glue */
#define FN_gfx_GetColorMap                       0x17A56  /* platform_video, library glue */
#define FN_gfx_InitBitMap                        0x17A62  /* platform_video, library glue */
#define FN_gfx_InitRastPort                      0x17A74  /* platform_video, library glue */
#define FN_gfx_InitView                          0x17A80  /* platform_video, library glue */
#define FN_gfx_InitVPort                         0x17A8C  /* platform_video, library glue */
#define FN_gfx_LoadRGB4                          0x17A98  /* platform_video, library glue */
#define FN_gfx_LoadView                          0x17AAA  /* title_select, void(View *v) */
#define FN_gfx_MakeVPort                         0x17AB6  /* platform_video, library glue */
#define FN_gfx_Move                              0x17AC4  /* platform_video, library glue */
#define FN_gfx_MrgCop                            0x17AD6  /* platform_video, library glue */
#define FN_gfx_OpenFont                          0x17AE2  /* platform_video, library glue */
#define FN_gfx_OwnBlitter                        0x17AEE  /* platform_video, library glue */
#define FN_gfx_RectFill                          0x17AF6  /* platform_video, library glue */
#define FN_gfx_ScrollRaster                      0x17B08  /* platform_video, library glue */
#define FN_gfx_SetAPen                           0x17B24  /* platform_video, library glue */
#define FN_gfx_SetBPen                           0x17B34  /* platform_video, library glue */
#define FN_gfx_SetDrMd                           0x17B44  /* platform_video, library glue */
#define FN_gfx_SetFont                           0x17B54  /* platform_video, library glue */
#define FN_gfx_Text                              0x17B64  /* platform_video, library glue */
#define FN_gfx_TextLength                        0x17B7E  /* platform_video, library glue */
#define FN_gfx_WaitBlit                          0x17B92  /* platform_video, library glue */
#define FN_gfx_WaitTOF                           0x17B9A  /* platform_video, library glue */
#define FN_icon_FindToolType                     0x17BA2  /* platform_video, library glue */
#define FN_icon_FreeDiskObject                   0x17BB0  /* platform_video, library glue */
#define FN_icon_GetDiskObject                    0x17BBC  /* platform_video, library glue */
#define FN_int_CloseWindow                       0x17BC8  /* platform_video, library glue */
#define FN_int_CloseWorkBench                    0x17BD4  /* platform_video, library glue */
#define FN_int_DrawImage                         0x17BDC  /* platform_video, library glue */
#define FN_con_RawKeyConvert                     0x17BF0  /* platform_video, library glue */
#define FN_run_intro                             0x1AED0  /* title_select, int(void) */
#define FN_intro_accolade_bull                   0x1B2B2  /* title_select, void(Archive *titleCar) */
#define FN_intro_testdrive_car                   0x1B396  /* title_select, void(Archive *titleCar) */
#define FN_intro_testdrive_logo                  0x1B62E  /* title_select, void(Archive *titleCar) */
#define FN_car_select                            0x1B8E6  /* title_select, int(void) */
#define FN_showroom_display_init                 0x1BA7C  /* title_select, void(void) */
#define FN_showroom_display_free                 0x1BC64  /* title_select, void(void) */
#define FN_car_pics_free_all                     0x1BD14  /* title_select, void(void) */
#define FN_load_file_retry                       0x1BD9C  /* title_select, void *(char *name) */
#define FN_show_car                              0x1BDCA  /* title_select, void(int idx View *view int dir) */
#define FN_sb_load_ilbm                          0x1BF40  /* title_select, void(long *data View *view) */
#define FN_sb_parse_ilbm                         0x1BF8E  /* title_select, void(char *form View *view) */
#define FN_sb_decode_body                        0x1C068  /* title_select, void(BMHD *bmhd uint *colors char *body  */
#define FN_colormap_clear                        0x1C15C  /* title_select, void(ColorMap *cm) */
#define FN_fade_plate_colours                    0x1C190  /* title_select, void(void) */
#define FN_wait_frames                           0x1C22A  /* title_select, void(int n) */
#define FN_showroom_drive_away                   0x1C244  /* title_select, void(int idx) */
#define FN_show_view                             0x1C62E  /* title_select, void(View *v) */
#define FN_scroll_out_down                       0x1C682  /* title_select, void(View *v) */
#define FN_scroll_in_up                          0x1C700  /* title_select, void(View *v) */
#define FN_scroll_out_up                         0x1C76A  /* title_select, void(View *v) */
#define FN_scroll_in_down                        0x1C7CC  /* title_select, void(View *v) */
#define FN_scroller_task_entry                   0x1C820  /* title_select, task entry */
#define FN_start_scroller                        0x1C83C  /* title_select, void(int up View *v) */
#define FN_run_game                              0x1C900  /* game_flow, int(int car) */
#define FN_traffic_reset                         0x1CCF6  /* drive_sim, void(void) */
#define FN_knob_update                           0x1CD72  /* drive_sim, void(void) */
#define FN_dealership_ending                     0x1CF76  /* drive_scene, void(void) */
#define FN_plot_pixel_set                        0x1D27E  /* drive_scene, asm d0 x d1 y */
#define FN_plot_pixel_clear                      0x1D2C2  /* drive_scene, asm d0 x d1 y */
#define FN_mul_scale                             0x1D306  /* drive_scene, asm d0.l=(s16)d0*D:0B62 */
#define FN_clamp_word                            0x1D31A  /* drive_sim, asm(d0 lo; d1 hi; a3 *word) */
#define FN_road_record                           0x1D32A  /* drive_sim, asm(d7 unit) -> a2 */
#define FN_set_main_window_clip                  0x1D36C  /* drive_scene, asm */
#define FN_render_frame                          0x1D392  /* drive_scene, void(View *back) */
#define FN_road_drawer_main                      0x1D484  /* drive_scene, task body */
#define FN_stage_score                           0x1D560  /* game_flow, long(long frames long par int factor) */
#define FN_play_again_menu                       0x1D5C8  /* game_flow, int(void) */
#define FN_clear_window                          0x1D97C  /* drive_scene, asm */
#define FN_queue_reset                           0x1D9C6  /* drive_scene, asm */
#define FN_compose_road_window                   0x1D9CC  /* drive_scene, asm */
#define FN_draw_road_main                        0x1DA14  /* drive_scene, asm */
#define FN_init_row_scale                        0x1DA72  /* drive_scene, asm */
#define FN_draw_road_mirror                      0x1DAA2  /* drive_scene, asm */
#define FN_set_mirror_window_clip                0x1DAF6  /* drive_scene, asm */
#define FN_road_edge_check                       0x1DB36  /* drive_sim, asm */
#define FN_traffic_spawn                         0x1DB90  /* drive_sim, asm(a2; d7) */
#define FN_radar_zone_start                      0x1DC08  /* drive_sim, asm(a2) */
#define FN_road_object                           0x1DC2E  /* drive_sim, asm(a2 rec; d7 unit) */
#define FN_speed_sign                            0x1DCA0  /* drive_sim, asm */
#define FN_heading_step                          0x1DCDC  /* drive_sim, asm(a2) */
#define FN_pitch_step                            0x1DD10  /* drive_sim, asm(a2) */
#define FN_row_scale_step                        0x1DD34  /* drive_scene, asm */
#define FN_row_y_step                            0x1DD56  /* drive_scene, asm */
#define FN_row_slope_step                        0x1DD96  /* drive_scene, asm */
#define FN_traffic_update                        0x1DDEA  /* drive_sim, void(int unit) */
#define FN_queue_slot_car_0                      0x1E062  /* drive_scene, asm */
#define FN_queue_slot_car_1                      0x1E078  /* drive_scene, asm */
#define FN_queue_slot_car_2                      0x1E08E  /* drive_scene, asm */
#define FN_queue_slot_car_3                      0x1E0A4  /* drive_scene, asm */
#define FN_queue_slot_car_4                      0x1E0B8  /* drive_scene, asm */
#define FN_queue_police_car                      0x1E0CC  /* drive_scene, asm */
#define FN_queue_oncoming_cars                   0x1E19E  /* drive_scene, asm */
#define FN_queue_post                            0x1E216  /* drive_scene, asm */
#define FN_queue_scenery_wed                     0x1E230  /* drive_scene, asm */
#define FN_queue_scenery_rock                    0x1E276  /* drive_scene, asm */
#define FN_queue_scenery_lin                     0x1E2B0  /* drive_scene, asm */
#define FN_queue_hazard                          0x1E2F8  /* drive_scene, asm */
#define FN_walk_road_rows                        0x1E314  /* drive_scene, asm */
#define FN_road_advance                          0x1E53A  /* drive_sim, void(void) */
#define FN_row_widths                            0x1E5C6  /* drive_scene, asm */
#define FN_draw_ticket                           0x1E63A  /* drive_scene, asm */
#define FN_draw_lane_marks                       0x1E65C  /* drive_scene, asm */
#define FN_shoulder_bump                         0x1E6A6  /* drive_sim, asm(d7) */
#define FN_rumble_slow                           0x1E720  /* drive_sim, asm */
#define FN_marker_test                           0x1E73A  /* drive_sim, asm(d2) */
#define FN_draw_clouds                           0x1E758  /* drive_scene, asm */
#define FN_blit_clouds                           0x1E784  /* drive_scene, asm */
#define FN_draw_bugs                             0x1E7D2  /* drive_scene, asm */
#define FN_move_clouds                           0x1EAE0  /* drive_scene, asm d0=4*dheading */
#define FN_wrap_cloud_x                          0x1EB5E  /* drive_scene, asm */
#define FN_init_clouds                           0x1EB78  /* drive_scene, void(void) */
#define FN_wrap_angle_delta                      0x1EBA8  /* drive_scene, asm */
#define FN_draw_cockpit_overlays                 0x1EBC4  /* drive_scene, asm */
#define FN_radar_zone                            0x1EC1A  /* drive_sim, void(long pos) */
#define FN_draw_radar_detector                   0x1EC94  /* drive_scene, asm */
#define FN_draw_steering_wheel                   0x1ED06  /* drive_scene, asm */
#define FN_xor_wheel_pose                        0x1ED64  /* drive_scene, asm d0 pose */
#define FN_reset_wheel_state                     0x1ED8A  /* drive_scene, void(int keep) */
#define FN_window_rect_stub                      0x1EDAE  /* drive_scene, asm */
#define FN_shift_gear                            0x1EDCE  /* drive_sim, void(int delta) */
#define FN_gate_select                           0x1EE76  /* drive_sim, void(int node) */
#define FN_cop_move_long                         0x1EF14  /* drive_scene, void(UCopList* long reg long value) */
#define FN_spr_pos_word                          0x1EF76  /* drive_scene, int(int h int v0 int v1 int att) */
#define FN_spr_ctl_word                          0x1EF90  /* drive_scene, int(int h int v0 int v1 int att) */
#define FN_cop_sprite_pos                        0x1EFD4  /* drive_scene, void(UCopList* h v0 v1 att n) */
#define FN_sprite_set_segment                    0x1F05A  /* drive_scene, void(int word int h int v0 int v1 int at */
#define FN_sprite_add_segment                    0x1F0DC  /* drive_scene, void(int h int v0 int v1 int att int n) */
#define FN_pack_shape_to_sprite                  0x1F12C  /* drive_scene, void(Shape* u16* dst int planes int col  */
#define FN_shape_to_sprite_segment               0x1F27E  /* drive_scene, void(Shape* int n int planes int col) */
#define FN_draw_needle                           0x1F2EA  /* drive_scene, void(int x int y int which) */
#define FN_position_wheel_marker                 0x1F582  /* drive_scene, void(int x int y) */
#define FN_sprites_init                          0x1F5BA  /* drive_scene, void(void) */
#define FN_sprites_free                          0x1F99A  /* drive_scene, void(void) */
#define FN_shake_dash_sprites                    0x1F9FE  /* drive_scene, void(void) */
#define FN_ucop_sprite_pointers                  0x1FAD4  /* drive_scene, void(UCopList*) */
#define FN_ucop_palette_split                    0x1FB4A  /* drive_scene, void(UCopList* u16* pal int line) */
#define FN_crash_windscreen_sequence             0x1FBD8  /* drive_scene, void(void) */
#define FN_redraw_cockpit_back                   0x1FDF4  /* drive_scene, void(void) */
#define FN_min16                                 0x1FE38  /* drive_scene, int(int int) */
#define FN_clamp_rgb4                            0x1FE54  /* drive_scene, int(int c int level) */
#define FN_fade_out_palette                      0x1FEAE  /* drive_scene, void(int delay u16* pal2 int line) */
#define FN_fill_row_span                         0x20096  /* drive_scene, asm a0 plane d4 off d1 x0 d2 x1 */
#define FN_fill_road_row                         0x20128  /* drive_scene, asm */
#define FN_fill_left_ground                      0x202A8  /* drive_scene, asm */
#define FN_draw_centre_line                      0x2031C  /* drive_scene, asm */
#define FN_draw_horizon_cliff                    0x2034E  /* drive_scene, asm */
#define FN_toggle_gear_box                       0x203E0  /* drive_scene, asm */
#define FN_queue_object                          0x20410  /* drive_scene, asm d0 x d1 y d2 code */
#define FN_draw_object_queue                     0x20456  /* drive_scene, asm */
#define FN_draw_obj_lin                          0x20526  /* drive_scene, asm */
#define FN_draw_obj_rock                         0x20546  /* drive_scene, asm */
#define FN_draw_obj_wed                          0x20562  /* drive_scene, asm */
#define FN_draw_obj_post                         0x20580  /* drive_scene, asm */
#define FN_scale_index5                          0x205A6  /* drive_scene, asm d4 */
#define FN_scale_index4                          0x205BC  /* drive_scene, asm d4 */
#define FN_draw_obj_traffic                      0x205CE  /* drive_scene, asm */
#define FN_draw_obj_sign_mirror                  0x206A0  /* drive_scene, asm */
#define FN_draw_obj_sign                         0x206E8  /* drive_scene, asm */
#define FN_draw_obj_hazard                       0x20740  /* drive_scene, asm */
#define FN_rpm_from_speed                        0x2076C  /* drive_sim, asm */
#define FN_speed_from_rpm                        0x20780  /* drive_sim, asm */
#define FN_shift_effects                         0x207A4  /* drive_sim, asm */
#define FN_engine_update                         0x20826  /* drive_sim, asm */
#define FN_detect_pitch_bump                     0x2090C  /* drive_scene, asm */
#define FN_dash_shake_update                     0x20940  /* drive_scene, asm */
#define FN_draw_digital_cluster                  0x2097C  /* drive_scene, asm */
#define FN_draw_number                           0x20A88  /* drive_scene, asm d0 a2 a3 */
#define FN_update_gauges                         0x20AF4  /* drive_scene, asm */
#define FN_sim_controls                          0x20CB0  /* drive_sim, void(void) */
#define FN_car_record_copy                       0x20D68  /* drive_sim, void(void) */
#define FN_stage_road_select                     0x20E70  /* drive_sim, void(int stage) */
#define FN_row_heading_step                      0x246FA  /* drive_scene, asm */
#define FN_row_x_step                            0x2472A  /* drive_scene, asm */
#define FN_update_wheel_marker                   0x247B2  /* drive_scene, asm */
#define FN_curve_integral                        0x2481C  /* drive_sim, asm(a2) */
#define FN_lateral_physics                       0x2484C  /* drive_sim, asm */
#define FN_steering                              0x24924  /* drive_sim, asm */
#define FN_steer_steps                           0x2498E  /* drive_sim, asm -> d0..d3 */
#define FN_edge_kicks                            0x249CC  /* drive_sim, asm -> d2 d3 */
#define FN_nop_24a02                             0x24A02  /* drive_sim, void(void) */
#define FN_grip_check                            0x24A04  /* drive_sim, asm */
#define FN_skid_drift                            0x24AA8  /* drive_sim, asm */
#define FN_stage_load                            0x24ACA  /* game_flow, void(int car) */
#define FN_stage_unload                          0x24CE4  /* game_flow, void(int keep) */
#define FN_remake_view                           0x24D68  /* drive_scene, void(View*) */
#define FN_setup_drive_copper                    0x24D8A  /* drive_scene, void(View*) */
#define FN_fade_out_drive                        0x24E52  /* drive_scene, void(void) */
#define FN_start_road_drawer                     0x24E94  /* drive_scene, void(void) */
#define FN_stop_road_drawer                      0x24F3A  /* drive_scene, void(void) */
#define FN_road_drawer_entry                     0x24F9A  /* drive_scene, task initPC */
#define FN_load_cockpit_shapes                   0x24FAA  /* drive_scene, void(void) */
#define FN_load_road_shapes                      0x253E6  /* drive_scene, void(void) */
#define FN_load_scenery_shapes                   0x25740  /* drive_scene, void(void) */
#define FN_load_sign_shapes                      0x259D8  /* drive_scene, void(void) */
#define FN_load_traffic_shapes                   0x2627C  /* drive_scene, void(void) */
#define FN_sfx_load_drive                        0x26B7A  /* platform_audio, void(void) */
#define FN_sfx_free_drive                        0x26C02  /* platform_audio, void(void) */
#define FN_radar_beep                            0x26C50  /* platform_audio, void(void) */
#define FN_engine_sound_start                    0x26C70  /* platform_audio, void(void) */
#define FN_engine_sound_fade_out                 0x26D16  /* platform_audio, void(void) */
#define FN_engine_sound_update                   0x26D4E  /* platform_audio, void(void) */
#define FN_squeal_update                         0x26E26  /* platform_audio, asm */
#define FN_bump_update                           0x26EE2  /* platform_audio, asm */
