"""Generate tdport/src/amiga/asymbols.h from port/amiga/symbols.csv.

Globals become    #define D_<name> 0xXXXX    (offset into the data hunk, the D:xxxx of the specs; use with the
                                               D8/D16/D32 accessors of tdport/src/amiga/amem.h)
Functions become  #define FN_<name> 0xXXXXX  (image addresses, for comments and traces)
Duplicate names get an _XXXX address suffix.
"""
import csv
import os
import re
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = list(csv.DictReader(open(os.path.join(ROOT, 'port', 'amiga', 'symbols.csv'), encoding='utf-8')))


def ident(name):
    name = re.sub(r'\W', '_', name)
    return ('_' + name) if name[:1].isdigit() else name


def addr(a):
    return int(a.replace('D:', '').replace('0x', ''), 16)


out = ['/* Generated by tools/gen_amiga_symbols.py from port/amiga/symbols.csv. Do not edit. */', '#pragma once', '']
for kind, prefix, title, width in (('global', 'D_', 'Data-hunk globals (D:xxxx offsets for D8/D16/D32)', 4),
                                   ('func', 'FN_', 'Original functions (image addresses)', 5)):
    sel = sorted((r for r in rows if r['kind'] == kind), key=lambda r: addr(r['address']))
    counts = Counter(ident(r['name']) for r in sel)
    out.append('/* %s */' % title)
    for r in sel:
        n = ident(r['name'])
        if counts[n] > 1:
            n = '%s_%04X' % (n, addr(r['address']))
        typ = r['type'].replace('*/', '* /')[:40]
        out.append('#define %-40s 0x%0*X  /* %s%s */' % (prefix + n, width, addr(r['address']), r['owner'],
                                                        (', ' + typ) if typ else ''))
    out.append('')

dst = os.path.join(ROOT, 'tdport', 'src', 'amiga', 'asymbols.h')
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('wrote', dst, sum(1 for r in rows if r['kind'] == 'global'), 'globals,',
      sum(1 for r in rows if r['kind'] == 'func'), 'functions')
