"""Generate tdport/src/symbols.h from port/symbols.csv (TDEGA) and port/cga/symbols_cga.csv (TDCGA).

DS globals become  #define DS_<name> 0xXXXX   (use with DSB/DSW/DSS/... from mem.h)
Functions become   #define FN_<name> 0xXXXX   (image offsets, for comments and traces)
Duplicate names get an _XXXX address suffix (the TDEGA address).
The TDCGA block (TD_CGA builds) defines only the symbols tools/xmap.py found in TDCGA.EXE, so code
that uses an EGA-only symbol fails to compile in a CGA build.
"""
import csv, os, re
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = list(csv.DictReader(open(os.path.join(ROOT, 'port', 'symbols.csv'), encoding='utf-8')))
cga_path = os.path.join(ROOT, 'port', 'cga', 'symbols_cga.csv')
cga = {(r['kind'], r['address']): r['cga'] for r in csv.DictReader(open(cga_path, encoding='utf-8'))}


def ident(name):
    name = re.sub(r'\W', '_', name)
    return ('_' + name) if name[:1].isdigit() else name


def addr(a):
    return int(a.replace('DS:', '').replace('0x', ''), 16)


def block(variant):
    out = []
    for kind, prefix, title in (('global', 'DS_', 'DGROUP globals (offsets for DSB/DSW/DSS/DSL)'),
                                ('func', 'FN_', 'Original functions (image offsets)')):
        sel = sorted((r for r in rows if r['kind'] == kind), key=lambda r: addr(r['address']))
        counts = Counter(ident(r['name']) for r in sel)
        out.append('/* %s */' % title)
        for r in sel:
            n = ident(r['name'])
            if counts[n] > 1:
                n = '%s_%04X' % (n, addr(r['address']))
            a = r['address'] if variant == 'ega' else cga.get((r['kind'], r['address']), '')
            if not a:
                continue
            typ = r['type'].replace('*/', '* /')[:40]
            out.append('#define %-40s 0x%04X  /* %s%s */' % (prefix + n, addr(a), r['owner'], (', ' + typ) if typ else ''))
        out.append('')
    return out


out = ['/* Generated by tools/gen_symbols.py from port/symbols.csv and port/cga/symbols_cga.csv. Do not edit. */',
       '#pragma once', '#include "build.h"', '', '#if TD_CGA', '/* ---- TDCGA.EXE */', '']
out += block('cga')
out += ['#else', '/* ---- TDEGA.EXE */', '']
out += block('ega')
out += ['#endif', '']

dst = os.path.join(ROOT, 'tdport', 'src', 'symbols.h')
open(dst, 'w', encoding='utf-8').write('\n'.join(out))
print('wrote', dst, sum(1 for r in rows if r['kind'] == 'global'), 'globals,', sum(1 for r in rows if r['kind'] == 'func'),
      'functions;', sum(1 for v in cga.values() if v), 'mapped to TDCGA')
