"""Generate tdport/src/amiga/font8.c from the "Amiga Topaz" OpenType font.

The Amiga's topaz 8 lives in the Kickstart ROM and is not on the game disk, so the port draws with a
recreation: the FontStruction "Amiga Topaz" by Patrick H. Lauke (https://fontstruct.com/fontstructions/show/675155),
licensed CC BY 3.0 (licenses/amiga-topaz/). Rendered at 16 px it is pixel-exact across and doubled
down, so taking every second row gives the original 8x8 cells (baseline row 6, 8-pixel advance).

    python tools/gen_font8.py amiga-topaz.otf.zip        (or a path to the .otf)
"""
import sys
import zipfile
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FIRST, LAST = 0x20, 0x7E
PX_X, PX_Y = 1, 2           # at 16 px the recreation is 1:1 across and doubled down
SIZE = 16


def glyph(font, ch):
    """The 8x8 cell of `ch` as 8 bytes (bit 7 = leftmost pixel), or None if the font has no glyph."""
    img = Image.new("L", (SIZE * 2, SIZE * 2), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255)
    rows, odd = [], []
    for y in range(8):
        bits = 0
        for x in range(8):
            block = [img.getpixel((x * PX_X + dx, y * PX_Y + dy)) > 127
                     for dx in range(PX_X) for dy in range(PX_Y)]
            if any(block) and not all(block):
                odd.append((x, y))
            if sum(block) * 2 >= len(block):
                bits |= 0x80 >> x
        rows.append(bits)
    return rows, odd


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "amiga-topaz.otf.zip")
    if src.suffix == ".zip":
        with zipfile.ZipFile(src) as z:
            data = z.read(next(n for n in z.namelist() if n.endswith(".otf")))
    else:
        data = src.read_bytes()
    font = ImageFont.truetype(BytesIO(data), SIZE)

    out = ['/* Generated by tools/gen_font8.py. Do not edit.',
           ' *',
           ' * The 8x8 font the port draws with, in place of the Amiga\'s topaz 8 (which lives in the Kickstart ROM,',
           ' * not on the game disk): the FontStruction "Amiga Topaz" by Patrick H. Lauke,',
           ' * https://fontstruct.com/fontstructions/show/675155, licensed CC BY 3.0 (licenses/amiga-topaz/),',
           ' * rasterised here to 8x8 cells. Baseline row 6, 8-pixel advance; rows are bytes, bit 7 leftmost. */',
           '#include "font8.h"', '',
           f'const u8 font8_first = 0x{FIRST:02X}, font8_last = 0x{LAST:02X};', '',
           f'const u8 font8_glyphs[{LAST - FIRST + 1}][8] = {{']
    missing = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        rows, odd = glyph(font, ch)
        if odd:
            print(f"note: {ch!r} has pixels off the grid at {odd[:4]}")
        if not any(rows) and ch != " ":
            missing.append(ch)
        label = ch if ch not in "\\'" else "\\" + ch
        out.append("    { %s },  /* %02X '%s' */" % (", ".join(f"0x{r:02X}" for r in rows), code, label))
    out += ["};", "",
            "/* Row r (0 = top) of character c; characters outside the table draw a hollow box. */",
            "u8 font8_row(u8 c, int r)",
            "{",
            "    static const u8 box[8] = { 0x00, 0x7E, 0x42, 0x42, 0x42, 0x42, 0x7E, 0x00 };",
            "    if (r < 0 || r >= 8) return 0;",
            "    if (c < font8_first || c > font8_last) return box[r];",
            "    return font8_glyphs[c - font8_first][r];",
            "}", ""]
    dst = ROOT / "tdport" / "src" / "amiga" / "font8.c"
    dst.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print("wrote", dst, "-", LAST - FIRST + 1, "glyphs")
    if missing:
        print("no pixels for:", " ".join(missing))


if __name__ == "__main__":
    main()
