"""Generate tdport/src/symbols.h from port/symbols.csv.

DS globals become  #define DS_<name> 0xXXXX   (use with DSB/DSW/DSS/... from mem.h)
Functions become   #define FN_<name> 0xXXXX   (image offsets, for comments and traces)
Duplicate names get an _XXXX address suffix.
"""
import csv, os, re
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = list(csv.DictReader(open(os.path.join(ROOT, 'port', 'symbols.csv'), encoding='utf-8')))


def ident(name):
    name = re.sub(r'\W', '_', name)
    return ('_' + name) if name[:1].isdigit() else name


def addr(r):
    return int(r['address'].replace('DS:', '').replace('0x', ''), 16)


out = ['/* Generated by tools/gen_symbols.py from port/symbols.csv. Do not edit. */', '#pragma once', '']
for kind, prefix, title in (('global', 'DS_', 'DGROUP globals (offsets for DSB/DSW/DSS/DSL)'),
                            ('func', 'FN_', 'Original functions (image offsets)')):
    sel = sorted((r for r in rows if r['kind'] == kind), key=addr)
    counts = Counter(ident(r['name']) for r in sel)
    out.append('/* %s */' % title)
    for r in sel:
        n = ident(r['name'])
        if counts[n] > 1:
            n = '%s_%04X' % (n, addr(r))
        typ = r['type'].replace('*/', '* /')[:40]
        out.append('#define %-40s 0x%04X  /* %s%s */' % (prefix + n, addr(r), r['owner'], (', ' + typ) if typ else ''))
    out.append('')

dst = os.path.join(ROOT, 'tdport', 'src', 'symbols.h')
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, 'w', encoding='utf-8').write('\n'.join(out))
print('wrote', dst, sum(1 for r in rows if r['kind'] == 'global'), 'globals,', sum(1 for r in rows if r['kind'] == 'func'), 'functions')
